version: "3.7"
services:
  api:
    depends_on: 
      - neo4j
    build: images/discovery-index
    image: oneilsh/discovery-index:0.1.3
    ports: 
      - "8000:8000"
    env_file:
      - images/discovery-index/git-crypt/RUN_VARS

  neo4j:
    image: neo4j:3.5
    ports:
      - "7474:7474"
      - "7687:7687"
    env_file:
      - images/discovery-index/git-crypt/RUN_VARS

