version: "3.7"
services:
  api:
    depends_on: 
      - neo4j
    build: images/discovery-index
    image: oneilsh/discovery-index:0.1.3
    ports: 
      - "443:443"
    environment:
      - PORT=443
      - NEO_4J_ENDPOINT=http://neo4j:7474/db/data/cypher
    env_file:
      - images/discovery-index/git-crypt/RUN_VARS

  neo4j:
    image: neo4j:3.5
    environment:
      NEO4J_dbms_connector_https_advertised__address: discovery-index.dldna.info:8483
      NEO4J_dbms_connector_https_listen__address: 0.0.0.0:8483
      NEO4J_dbms_connector_http_advertised__address: discovery-index.dldna.info:8484
      NEO4J_dbms_connector_http_listen__address: 0.0.0.0:8484
      NEO4J_dbms_connector_bolt_advertised__address: discovery-index.dldna.info:8687
      NEO4J_dbms_connector_bolt_advertised__address: 0.0.0.0:8687
      NEO4J_dbms_logs_debug_level: DEBUG
    ports:
      - "8483:8483"
      - "8484:8484"
      - "8687:8687"
    env_file:
      - images/discovery-index/git-crypt/RUN_VARS


